# Generated by Django 2.1.3 on 2018-11-27 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Category name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
        migrations.AlterField(
            model_name='project',
            name='percent',
            field=models.IntegerField(default=5, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'), (0, '0')], default=8, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='percent',
            field=models.IntegerField(default=5, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='priority',
            field=models.IntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'), (0, '0')], default=8, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='project',
            name='categorys',
            field=models.ManyToManyField(blank=True, to='core.Category'),
        ),
    ]
