# Generated by Django 2.1.2 on 2018-11-02 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunch',
            name='users',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='active_bunch',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bunch',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bunch',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
