# Generated by Django 2.1.2 on 2018-11-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181102_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=10)),
                ('percent', models.IntegerField(default=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-priority', '-percent']},
        ),
        migrations.AddField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.Project'),
        ),
    ]
