# Generated by Django 2.1.2 on 2018-11-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181102_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectreview',
            options={'ordering': ['-create_at']},
        ),
    ]
